version: '3.7'

services:

  db:
    network_mode: host
    image: postgres:12
    command: -p 5431  # Non-default port to avoid failed binding
    ports:
      - '5431:5431'  # Non-default port to avoid failed binding
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
    environment:
      - POSTGRES_DB=csv_bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  flask-api:
    network_mode: host
    restart: always
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"

  client:
    network_mode: host
    build:
      context: client
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    volumes:
      - './client:/usr/src/app'
      - './client/node_modules:/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:5000
