version: '3.5'

services:

  db:
    image: postgres
    container_name: postgres
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=csv_bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'

  flask-api:
    container_name: csv-bank-flask
    restart: always
    build:
      context: csv_bank_backend/
      dockerfile: Dockerfile
    ports:
      - "8000"
    volumes:
      - ./csv_bank_backend:/usr/src/app
    depends_on:
      - "db"

  client:
    container_name: csv-bank-react
    build:
      context: csv_bank_client
      dockerfile: Dockerfile
    volumes:
      - './csv_bank_client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "flask-api"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:5000
